[tool.poetry]
name = "penguins"
version = "2.0.0"
description = "DBCA Little Penguins Observations application"
authors = ["Ashley Felton <ashley.felton@dbca.wa.gov.au>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
django = "5.1.3"
psycopg = {version = "3.2.3", extras = ["binary", "pool"]}
dbca-utils = "2.0.2"
python-dotenv = "1.0.1"
dj-database-url = "2.2.0"
django-extensions = "3.2.3"
gunicorn = "23.0.0"
whitenoise = { version = "6.7.0", extras = ["brotli"] }
django-storages = { version = "1.14.4", extras = ["azure"] }
webtemplate-dbca = "1.7.1"
django-map-widgets = "0.5.1"
xlsxwriter = "3.2.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.28.0"
ipdb = "^0.13.11"
pre-commit = "^4.0.1"

# Reference: https://docs.astral.sh/ruff/configuration/
[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
  "E501", # Line too long
  "E722", # Bare except
]

# Reference: https://www.djlint.com/docs/configuration/
[tool.djlint]
profile = "django"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
