apiVersion: batch/v1
kind: CronJob
metadata:
  name: penguins-import-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: penguins-import-cronjob
            args: ["manage.py", "video_import"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: penguins-env-uat
                  key: DATABASE_URL
            - name: AZURE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: penguins-env-uat
                  key: AZURE_ACCOUNT_NAME
            - name: AZURE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: penguins-env-uat
                  key: AZURE_ACCOUNT_KEY
            - name: AZURE_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: penguins-env-uat
                  key: AZURE_CONTAINER
