apiVersion: batch/v1
kind: CronJob
metadata:
  name: penguins-import-cronjob
spec:
  # x minutes past the hour, every hour.
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: penguins-import-cronjob
              args: ["manage.py", "video_import"]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: penguins-env-prod
                      key: DATABASE_URL
                - name: AZURE_ACCOUNT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: penguins-env-prod
                      key: AZURE_ACCOUNT_NAME
                - name: AZURE_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: penguins-env-prod
                      key: AZURE_ACCOUNT_KEY
                - name: AZURE_CONTAINER
                  valueFrom:
                    secretKeyRef:
                      name: penguins-env-prod
                      key: AZURE_CONTAINER
